# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Anbulance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anbulance

  target 'AnbulanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnbulanceUITests' do
    # Pods for testing
  end

  
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  
  
end
